### ISSUE TITLE
IRIS loading 0 channels

### ISSUE THREAD

**Issue by gr8hayz5** [tombowditch/telly#235]
**telly release with the issue:**

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

**I wanted the simplest setup so I signed up for Vader and plugged my credentials into the Config file and had no luck, I later found out that vader no long works with telly. So now i have signed up for IRIS and plugged my credentials into the config file and YES its loaded!!! but it loaded 0 channels into the lineup. They did not provide me with an EPG link and I also don't see anywhere to enter an epg link for IRIS. I do have a schedules direct account but it looks like that would have only worked with Vaders. Any Idea why IRIS isn't loading the channels?

Thanks!!**

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**

**Comment by chazlarson** [comment]
Perhaps bring this over to the discord; easier communication for this sort of support issue.  Chances are the 0 channels thing is a filter issue.

The iris EPG link is "http://irislinks.net:83/xmltv.php?username=${IPTVUSER}&password=${IPTVPASS}"

discord: https://discord.gg/bnNC8qX

If that's not possible, please provide:
Version of telly
Config file contents [with credentials redacted] if appropriate

**Comment by chazlarson** [comment]
There are some possible causes here, assuming you're using 1.1:
https://github.com/tellytv/telly/wiki/No-channels---1.1

**Comment by gr8hayz5** [comment]
Thank You, it was the filter that blocked the channels. Now I am stuck trying to figure out how to use the filter. I was trying to follow the directions in the link within the link that you sent me, but I don't get it.

Example if I wanted all local chicago channels it would be easy to do this:

 Filter = "chicago"
 FilterKey = "group-title" 
 FilterRaw = true         
 Sort = "group-title"

but if i want to add ESPN and NFL Network and HBO how do I add on to that filter.

Even better how to I remove all filters so I can just uncheck the channels that I don't want during the Plex part of the setup.

Thanks :)

**Comment by chazlarson** [comment]
I'd be interested in discussing how this article can be improved:
https://github.com/tellytv/telly/wiki/Running-Telly%3A-Filtering

I think all these questions are covered in there, but if it's not clear I'd like to improve it.

```
Filter = "chicago"
```
That's the regular expression that telly will apply to the list of channels.  Any channel that matches this expression will pass through.  You can use some standard regular expression syntax in there, but the most common thing people do with telly is OR.  The syntax for OR is `"this|that"`.

In your case, you want channels that have "chicago" OR "ESPN" OR "NFL" OR "HBO", which you could express as `"chicago|ESPN|NFL|HBO"`

```
FilterKey = "group-title"
```
This is the key in the m3u to which the expression is applied.

```
FilterRaw = true
```
IF this is "true" the expression is applied to the line as a whole, without regard for m3u fields.  If it's true, in effect the FilterKey is ignored.

```
Sort = "group-title"
```
Telly will then sort the filtered channels by the contents of this field.

Modifying your example:
```
Filter = "chicago|ESPN|NFL|HBO"
FilterKey = "group-title"
FilterRaw = true
Sort = "group-title"
```

That will allow any channel that contains any of those strings [chicago or ESPN or NFL or HBO] ANYWHERE in the channel information line.  The resulting list of channels will be sorted by the contents of the "group-title" field.

You can eliminate the filter behavior by:
1. commenting those lines out in the config file OR
1. setting the filter to "."
This won't do what you want, though, because that will result in telly quitting at launch because your playlist contains thousands of channels.  Plex doesn't behave well if there are more than 420 channels published by the tuner, so telly doesn't allow that.

**Comment by gr8hayz5** [comment]
Ok what you say here makes sense. I will explain the one thing I can not
figure out. If i have list like the one below that includes  USA: ESPN it
will bring in over 40 channels with ESPN in the title but I only want
specific ESPN channels including the original ESPN.

  Filter = "USA: CBS 2 WBBM|USA: NBC 5 WMAQ|USA: ABC 7 WLS|CA: WGN|USA: FOX
32 WFLD|LATINO: Telemundo 44 WSNS|USA: MY 50 WPWR|USA: CNN|USA: ESPN|USA:
ESPN 2|USA: ESPN NEWS|USA: ESPN U|USA: NFL NETWORK"

Thanks!

**Comment by chazlarson** [comment]
You're filtering on `group-title`?  If so, this is not unexpected, since that group probably contains all those unwanted channels.  An alternative would be to set the filter key to `tvg-id` or `tvg-name`, and enter just the specific channels you want based on one of those fields.

**Comment by chazlarson** [comment]
Closing since this seems to be sorted.
