### ISSUE TITLE
Stream Don't start

### ISSUE THREAD

**Issue by sheryus** [tombowditch/telly#261]
i run channel and i have this:
![image](https://user-images.githubusercontent.com/20800089/64937641-528b5f80-d85b-11e9-88e6-3fb602439b0a.png)

**Comment by chazlarson** [comment]
Can't say much without configuration details, but it looks like FFMPEG is disabled in your config, and telly is behaving as expected.  It's issuing a redirect to the provider stream, and is not involved after that.

There are some articles in the wiki that discuss how you can get more information about what's going on here.  They also show what a successful "tune a channel" event looks like in the log.

https://github.com/tellytv/telly/wiki/Connection-issues---1.1

Please review and try the suggestions there; if you need further help please include your config file and the out you're seeing from both `telly` and `curl`.  It would be helpful to paste it in rather than using screenshots.  Thanks!
